import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { GradientBars } from '@/components/ui/gradient-bars';
import "../globals.css";

import LandingNavBar from './landing-navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Gradient background absolutely positioned */}
        <div className="absolute inset-0 -z-10 pointer-events-none w-full h-full bg-neutral-200 dark:bg-neutral-800">
          <GradientBars />
        </div>
        <LandingNavBar />
        {children}
      </body>
    </html>
  );
}
